version: '3'
services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./apache-config/httpd.conf:/etc/apache2/sites-available/000-default.conf
      - ./homework:/var/www/html